# https://github.com/marketplace/actions/github-readme-stats-action?version=v1.1.0

name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      # - name: Generate stats card
      #   uses:  soulteary/github-readme-stats-action@v1.0.0
      #   with:
      #     card: stats
      #     options: username=${{ github.repository_owner }}&theme=transparent&title_color=#478be6&show_icons=true&cache_seconds=7200&hide=prs,issues
      #     path: .github/profile/stats.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=${{ github.repository_owner }}&theme=transparent&title_color=#478be6&layout=compact&langs_count=10'
          path: .github/profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate trophy card
      #   uses: soulteary/github-profile-trophy-action@v1.0.0
      #   with:
      #     options: 'username=${{ github.repository_owner }}&theme=transparent&title_color=#478be6&column=7&margin-w=15&margin-h=15&title=AllSuperRank,MultiLanguage,Stars,Commits,Follower,Issues,PullRequest&show_icons=true'
      #     path: .github/profile/trophy.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push